baseURL = 'https://marcoferra.com/'
languageCode = 'en-us'
title = 'marcoferra.com'

theme = 'stardust'

disableKinds = ['taxonomy', 'term']

disableLiveReload = true

disableHugoGeneratorInject = true
